import { ClerkProvider } from "@clerk/nextjs"
import "../globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary: "bg-[#48cae4] hover:bg-blue-300 text-sm "
        }
      }}
    >
      <html lang="en">
        <body className="w-full min-h-screen flex justify-center items-center bg-[#48cae4]">
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
